name: portaleWhlive
version: 0.0.1

environment:
  sdk: '>=2.8.4 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+22
  meta: ^1.1.8
  mysql1: ^0.17.1

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  sass_builder: ^2.1.3
